### ISSUE TITLE
Undefined background color in the HTML report output

### ISSUE THREAD

**Issue by petrpisaratlascz** [lvc/abi-compliance-checker#13]
Current HTML style defines text color, but does not define background color. Because default colors are implementation dependent, it can happen then an HTML viewer will render a black text on a black background. This is the current CSS code from the Report.css:

```
body {
    font-family:Arial, sans-serif;
    color:Black;
    font-size:14px;
}
```

Please add a background-color property with a value you think it matches best to colors you are using in the output.

**Comment by aponomarenko** [comment]
Fixed in 1.99.10.

Thank you.
