### ISSUE TITLE
False positive due to white space change

### ISSUE THREAD

**Issue by michihenning** [lvc/abi-compliance-checker#25]
With version 1.99.14.1, I just noticed a false positive in the HTML report:

Type of return value has been changed from

    std::map<std::__cxx11::string,std::__cxx11::string>
 to

    std::map<std::__cxx11::string, std::__cxx11::string>

Note trailing comma separating the template parameters.

**Comment by michihenning** [comment]
Sorry, "trailing white space following the comma…"

Somehow the copy and paste got messed up.

Christ... As soon as I mention an angle bracket, some bloody interpreter kicks in and makes a mess of what I write. The problem is that I have a map of string, string pairs. The false positive is that, in one version, I'm told that the template parameters are "string,string", and in the other, "string, string" (note the space following the comma). There are dozens of false positives like this. It looks like it happens whenever there is a template with two parameters.

Sorry to be so obtuse, but there doesn't appear to be any way to disable the broken post-processing of what I write here. Angle brackets are off-limits, it seems :-(

If this doesn't make sense, let me know, and I'll upload a screenshot tomorrow.

**Comment by aponomarenko** [comment]
Thank you for reporting this. I've fixed it in master branch. Please check if it works for your library. I'll prepare the release if all is OK.

**Comment by michihenning** [comment]
Thank you very much, works perfectly! :-)  And thank you again for the super-fast response!
