### ISSUE TITLE
abi-compliance-checker no longer works on hurd

### ISSUE THREAD

**Issue by ellert** [lvc/abi-compliance-checker#26]
I forward a bug I submitted to the Debian bug tracker:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805441

See the above link for details.

**Comment by lvc** [comment]
Thank you for reporting this issue. Could you please point me to the proper Live CD or DVD (ISO) of the Debian Hurd, so I can debug and fix it?

**Comment by ellert** [comment]
https://www.debian.org/ports/hurd/hurd-cd
