### ISSUE TITLE
how to define multiple macros with your option -gcc-options ?

### ISSUE THREAD

**Issue by zhangfan5494** [lvc/abi-compliance-checker#28]
We can define multiple macros with gcc -Dmacro1 -Dmacor2, but it seems that -gcc-options -Dmacro1 -Dmacro2 would lead to a failure, could you give some comments on how to use -gcc-options to define mutiple macros ?

**Comment by aponomarenko** [comment]
Hello. Thank you for reporting the issue.

You can specify the value of this option in quotes:

    abi-compliance-checker ... -gcc-options "-Dmacro1 -Dmacro2"

Also you can use `defines` option of the xml-descriptor:

    <defines>
        #define macro1
        #define macro2
    </defines>

Also please note that there exists an alternative way to analyse binary compatibility using the abi-dumper tool (https://github.com/lvc/abi-dumper). It's more reliable way that doesn't require compilation of the header files.

**Comment by zhangfan5494** [comment]
Thanks a lot :)
