### ISSUE TITLE
Error with extern APIS

### ISSUE THREAD

**Issue by jothiprasath** [lvc/abi-compliance-checker#33]
Hello,

 I'm trying to create a dump for a library for which i'm getting an error "error: expected constructor, destructor, or type conversion before ‘(’ token". 
This is happening only for the API which is declared as extern in the header file. 
How should the extern API declaration need to be handled for ABI dump?

**Comment by aponomarenko** [comment]
Hello.

Thank you for reporting issues.

There are 2 ways to create ABI dumps:

1. Via the abi-compliance-checker tool
2. Via the abi-dumper tool: http://lvc.github.io/abi-compliance-checker/#ABI_Dumper

The abi-compliance-checker executes the g++ on input header files with some additional options for analysis. Are your header files can be compiled by g++ without such errors?

The second way doesn't require compilation of any header files, so it may help you.

Thank you.

**Comment by jothiprasath** [comment]
Hello

Thanks for your quick response.
I'm using compliance checker tool to create the dump.
I tried using g++ forcefully instead of gcc to compile the headers with
abi. Used - - gcc-path option to set g++ compiler.
But still i got the same error for extern API.

Thanks & Regards,
Jothiprasath

**Comment by aponomarenko** [comment]
Please try to run g++ directly on the problem header file:

    g++ header.h

Thank you.

**Comment by jothiprasath** [comment]
Problem occurred from my side. Some of the dependencies were missing in the server on which i was trying to compile. Now i could able to run abi without any error in a server with all necessary dependencies.
Thank you for your patience and reply.
