### ISSUE TITLE
Warning about incompatible GCC version with GCC 4.8.4

### ISSUE THREAD

**Issue by v-lopez** [lvc/abi-compliance-checker#34]
I am execuing abi-compliance-checker from a Ubuntu 14.04 64b machine with GCC 4.8.4, but I get a warning about GCC 4.8.

I've looked at the source code, and afaik it should only affect versions between 4.8.0 and 4.8.2. The problem is that after the warning it sets EMERGENCY_MODE_48 to 1 and changes the behaviour of ACC.

Is it intended that version 4.8.4 is executed with EMERGENCY_MODE_48 enabled?

**Comment by aponomarenko** [comment]
Hello,

Thank you for reporting the issue.

The EMERGENCY_MODE_48 should not be set for gcc 4.8.4. Seems that this is a bug in the ACC.

Could you please post output of:

    gcc -dumpmachine

**Comment by aponomarenko** [comment]
And also please post output of:
    gcc -dumpversion

**Comment by v-lopez** [comment]
gcc -dumpmachine
> x86_64-linux-gnu

gcc -dumpversion

> 4.8

gcc --version

> gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
> Copyright (C) 2013 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

**Comment by lvc** [comment]
Fixed in the latest version. Please check.

Thank you.
