### ISSUE TITLE
Linux kernel

### ISSUE THREAD

**Issue by 1ace** [lvc/abi-compliance-checker#35]
Hi,

I'd love to be able to see changes in the kernel API from one version to the next (very useful for my work), but this tool seems unable to do it.
Have you tried that?  I might just be doing it wrong :]

I tried making a simple xml:
```xml
<version> 4.2.6 </version>
<headers> x86_64-4.2.6/include/ </headers>
<libs> x86_64-4.2.6/lib/ </libs>
```

But when I try to run it, they all give me the same
> Using C++ compatibility mode
> ERROR: some errors occurred when compiling headers
"C++ compatibility mode" seems suspicious, and I couldn't find any way to force it to C.

The log file explains a header could not be found:
```
In file included from /home/eric/dev/kernel/x86_64-4.2.6/include/acpi/platform/aclinux.h:165:0,
                 from /home/eric/dev/kernel/x86_64-4.2.6/include/acpi/platform/acenv.h:173,
                 from /home/eric/dev/kernel/x86_64-4.2.6/include/acpi/acpi.h:56,
                 from /home/eric/.tmp/zCGSkyLpQ5/dump1.h:3:
/home/eric/dev/kernel/x86_64-4.2.6/include/linux/string.h:17:24: fatal error: asm/string.h: No such file or directory
 #include <asm/string.h>
                        ^
compilation terminated.
```

I pretty tired, and wouldn't be surprised if I missed something obvious :)

**Comment by aponomarenko** [comment]
Hello,

You'd better to use the abi-dumper (https://github.com/lvc/abi-dumper) tool to create Linux kernel ABI dumps and then compare them by the ABICC to create API/ABI changes report. The kernel should be configured with these two additional options:

    CONFIG_DEBUG_INFO=y
    CONFIG_DEBUG_INFO_REDUCED=n

Then you can create ABI dumps from the vmlinux debug info:

    abi-dumper -o ABI-4.x.dump -lver 4.x vmlinux
    abi-dumper -o ABI-4.y.dump -lver 4.y vmlinux

And then compare ABI dumps to create report:

    abi-compliance-checker -l vmlinux -old ABI-4.x.dump -new ABI-4.y.dump

See also https://github.com/alexandernst/linux-kernel-compatibility-checker

**Comment by aponomarenko** [comment]
Two years ago I've tried this method and got some results: http://upstream.rosalinux.ru/kernel/

**Comment by 1ace** [comment]
Thanks, I'll try that next week :)

I had a quick look through your repo, and you should really use [git's submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) instead of copying all the files from your dependencies into your own repo ;)

**Comment by aponomarenko** [comment]
linux-kernel-compatibility-checker is not my repository. Please report this to Alexander at https://github.com/alexandernst/linux-kernel-compatibility-checker/issues

Thank you.

**Comment by 1ace** [comment]
Yeah, sorry about that, there's not excuse to have missed that xD

**Comment by lvc** [comment]
See also ABI report for the latest Linux kernels: http://abi-laboratory.pro/tracker/timeline/linux/

The report is generated by https://github.com/lvc/abi-tracker

Thank you.
