### ISSUE TITLE
Change from "void const *" to "void const volatile *" is reported as removed const

### ISSUE THREAD

**Issue by gqmelo** [lvc/abi-compliance-checker#39]
I was testing abi-compliance-checker (1.99.17) and tried with two versions of openssl, and this is what I got:

<a name='Medium_Risk_Binary_Problems'></a><a name='Symbol_Binary_Problems_Medium'></a><a name='Interface_Binary_Problems_Medium'></a>
<h2>Problems with Symbols, Medium Severity (2)</h2><hr/>
<span class='h_name'>crypto.h</span>, <span class='lib_name'>libcrypto.so.1.0.0</span><br/>
<span class="section" onclick="javascript:showContent(this, 'c_1')">
<span class='extendable'>[+]</span> CRYPTO_memcmp&#160;<span class='sym_p'>(&#160;<span class='nowrap'>void const* <span class='color_p'>a</span>,</span> <span class='nowrap'>void const* <span class='color_p'>b</span>,</span> <span class='nowrap'>size_t <span class='color_p'>len</span> )</span></span> (2)</span>
<br/>
<div id="c_1" style="display:none;">

<span class='new_sign_lbl'>changed to:</span><br/><span class='new_sign'>CRYPTO_memcmp&#160;<span class='sym_p'>(&#160;void const volatile* <span class='color_p'>a</span>, void const volatile* <span class='color_p'>b</span>, <span class='nowrap'>size_t <span class='color_p'>len</span> )</span></span></span><br/>
<table class='ptable'><tr><th width='2%'></th><th width='47%'>Change</th><th>Effect</th></tr><tr><th>1</th><td align='left' valign='top'>Type of <b>1st</b> parameter <b>a</b> has been changed from <span class='value'>void const*</span> to <span class='value'>void const volatile*</span> (removed const qualifier).</td><td align='left' valign='top'>This function may change parameter <b>a</b>, but it will be treated as const by old client applications. This may result in crash or incorrect behavior of applications.</td></tr>
<tr><th>2</th><td align='left' valign='top'>Type of <b>2nd</b> parameter <b>b</b> has been changed from <span class='value'>void const*</span> to <span class='value'>void const volatile*</span> (removed const qualifier).</td><td align='left' valign='top'>This function may change parameter <b>b</b>, but it will be treated as const by old client applications. This may result in crash or incorrect behavior of applications.</td></tr>
</table><br/>
</div>

**Comment by aponomarenko** [comment]
Hello, Guilherme.

Thanks for reporting this!

The issue has been fixed by the commit 9e05beee1bb110a2b6e13a36119c9893ed0c5414.

Please check new 1.99.18 version of the tool.

The report for OpenSSL has been updated: http://abi-laboratory.pro/tracker/timeline/openssl/

Thank you.

**Comment by gqmelo** [comment]
Thanks for the quick response!
I tested with the 1.99.18 and can confirm the issue is gone.
