### ISSUE TITLE
Addition or removal of data members from class or struct.

### ISSUE THREAD

**Issue by niranjankk12** [lvc/abi-compliance-checker#41]
The tool doesn't detect the addition or removal of data member from class. Is there any extra command line switch i need to provide i tried "-lang c++ -use-dumps" these switches.

**Comment by lvc** [comment]
Hello,

Do you mean static fields? In this case added/removed fields are reported as added/removed symbols. Is the added/removed field private or public? The tool doesn't report addition or removal of private fields if they don't affect size/alignment of the class.

Please run this command in the console:

    cd tmp/
    abi-compliance-checker -test

Please look at the AddedFieldAndSize/RemovedFieldAndSize classes in the report for C++ (`compat_reports/libsample_cpp/1.0_to_2.0/compat_report.html`) and post the console output of the tool here.

Thank you.

**Comment by niranjankk12** [comment]
I using it on windows, Following is the console output:

d:\BinaryCompatablity\abi-compliance-checker-1.99.17>abi-compliance-checker.pl -
test
Using GCC 5.1.0 (x86_64-w64-mingw32, target: x86_64)

verifying detectable C library changes
preparation, please wait ...
Using GCC 5.1.0 (x86_64-w64-mingw32, target: x86_64)
WARNING: the architectures of input objects and the used GCC compiler are not eq
ual, please change the compiler by --gcc-path=PATH option.
WARNING: the architectures of input objects and the used GCC compiler are not eq
ual, please change the compiler by --gcc-path=PATH option.
checking header(s) 1.0 ...
Using C++ compatibility mode
checking header(s) 2.0 ...
Using C++ compatibility mode
comparing ABIs ...
comparing APIs ...
creating compatibility report ...
WARNING: incomplete rule "Removed_Constant" ("Binary")
WARNING: incomplete rule "Removed_Constant" ("Source")
result: INCOMPATIBLE (Binary: 20.7%, Source: 13.2%)
total "Binary" compatibility problems: 36, warnings: 37
total "Source" compatibility problems: 24, warnings: 31
see detailed report:
  compat_reports/libsample_c/1.0_to_2.0/compat_report.html
ERROR: result: FAILED (60 problems found)

verifying detectable C++ library changes
ERROR: can't compile libsample_cpp v.1: 'libsample_cpp/libsample.v1/build-log.tx
t'

d:\BinaryCompatablity\abi-compliance-checker-1.99.17>

**Comment by lvc** [comment]
Hello,

Thanks for the info.

I haven't tested the tool on Windows about two years. This may be a regression or incompatibility with recent versions of the Visual Studio tools and MinGW. Also the tool is not tested yet with GCC 5.

I have one computer with Windows 7 and I'll try to test/debug the recent release on it soon.

Thanks for your help.

**Comment by niranjankk12** [comment]
Hi,

Thanks for the details.

Can you please let me know the release version you tested last time on windows? and the GCC version for the same.

**Comment by lvc** [comment]
Hi,

This is incompatibility with GCC 5.1. I've just reproduced the same bad test results on Linux. I'll try to fix it quickly.

The tool works with any GCC 4.x except 4.8.[0-2].

Thank you.

**Comment by lvc** [comment]
The latest version of the tool tested on Windows is 1.96.8 (too old, probably you'll not be able to find a tarball).

Thank you.

**Comment by lvc** [comment]
I've added support for GCC 5.1 in 1.99.19 version of the tool: https://github.com/lvc/abi-compliance-checker/releases

Please try new version.

Thank you.

**Comment by niranjankk12** [comment]
Thank you very much for quick update. I will try it and let you the results.
