### ISSUE TITLE
The affected elements are empty when generating XML report.

### ISSUE THREAD

**Issue by JamesQAQ** [lvc/abi-compliance-checker#44]
When I tried to generate XML report, I found the **affected** elements in **Problems with
Data Types**  are always empty.

In line [17023](https://github.com/lvc/abi-compliance-checker/blob/master/abi-compliance-checker.pl#L17023), I guess **$Kinds_Locations{$TypeName}** should be **\%Kinds_Locations** ?

**Comment by lvc** [comment]
Fixed by the commit f9f25c9b4ce17c950902c7e09935eccbca6309c5.

Thank you for reporting this issue.
