### ISSUE TITLE
Support for GCC 6

### ISSUE THREAD

**Issue by lvc** [lvc/abi-compliance-checker#49]
The tool doesn't work properly with GCC 6.2/6.1 due to GCC bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78040.

**Comment by zhuda** [comment]
@lvc the latest gcc I can gain on Windows seems still be 5.3 in [MingGW-w64](http://mingw-w64.org/doku.php/download) , and 5.3 didn't support many c++ 11 or 14 new features which lead build errors during compilation. 

Any idea on how to use ABI with latest c++ codes on Windows?

**Comment by lvc** [comment]
Hi,

Please checkout latest version of the ABICC 2.0 Beta from the master branch. It should work well with GCC 6.2.

Please also install `MinGW-W64 GCC-6.2.0` from https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.2.0/

Thank you.

**Comment by zhuda** [comment]
@lvc I checkout latest master branch and run with GCC6.2, seems the script still not ready for GCC 6.2?

>Preparing, please wait ...
Using GCC 6.2.0 (x86_64-w64-mingw32, target: x86_64)
ERROR: Not working properly with GCC 6.2.0. Please use other GCC version with the help of -
-gcc-path=PATH option. Not supported GCC versions: 4.8.0, 4.8.1, 4.8.2, 6.1.0, 6.2.0
Terminating on signal SIGBREAK(21)
Terminate batch job (Y/N)? y

**Comment by lvc** [comment]
It's not a critical problem. Please check if the tool works on your host by the command:

    abi-compliance-checker -test

It should print SUCCESS or FAILED.

**Comment by lvc** [comment]
I'll change this error to be a warning.

**Comment by zhuda** [comment]
Thanks, running -test it report success results. 
Is gcc 6.2 has regression on function? if not do you still mark it as warning?
