### ISSUE TITLE
Broken detection of abi problem

### ISSUE THREAD

**Issue by bastien-roucaries** [lvc/abi-compliance-checker#54]
Hi,

It seems report here is broken. File does not change.

May be you have discover a g++ bug https://abi-laboratory.pro/tracker/compat_report/imagemagick/6.9.7-2/6.9.7-3/d679a/abi_compat_report.html

**Comment by lvc** [comment]
Hi,

Thank you for reporting this bug.

I've regenerated ABI dumps for both versions and the problem went away. Seems that this was a bug in the ABI dumper.

Thank you.
