### ISSUE TITLE
difference access manner of same enum value be recognized as value changed

### ISSUE THREAD

**Issue by zhuda** [lvc/abi-compliance-checker#60]
Hi @lvc,

I got following error for a variable in my two builds:
![image](https://cloud.githubusercontent.com/assets/3140101/26668992/b8ccd3fc-46de-11e7-88aa-522f2a2da616.png)

And here is the difference of this variable's definitions in my two builds:
![image](https://cloud.githubusercontent.com/assets/3140101/26669099/1f50e622-46df-11e7-8714-5e2fe11ea6f8.png)

You can notice that the difference is just different access manner of the same enum value (with/without type scope).  basing on my test and the link these two definitions should be equivalent, do you know why this be treated as a error? The compatibility report for binary & source are both 100%, however the return value of perl script is 1, so I would guess this issue lead failed value (1) be returned.

Thanks,
Danny

**Comment by lvc** [comment]
Hello,

Thank you for the report.

The tool simply checks if the value of a #define macros is the same or not the same (without parsing it deeper).

Please add an option `--disable-constants-check` to disable report for such changes.

**Comment by zhuda** [comment]
ok, thanks!

**Comment by zhuda** [comment]
@lvc btw, `--disable-constants-check` means don't check constant globally, right?

**Comment by lvc** [comment]
Option `--disable-constants-check` disables checks for changes in #defines. Enumeration constants are still checked.
