### ISSUE TITLE
How to ignore typedef and variable name in function parameter list

### ISSUE THREAD

**Issue by zhuda** [lvc/abi-compliance-checker#63]
Hi @lvc , I have met a case like below, #1 is a typedef that act equivalent during runtime, #2 and #3 are both parameter value rename to be more meaningful, you have any suggestions how to ignore them when do bc check?

![image](https://user-images.githubusercontent.com/3140101/28010384-5260bd6e-6591-11e7-9010-8e086048b36b.png)

Thanks,
Danny

**Comment by aponomarenko** [comment]
Hi,

You can set `severity` of `Renamed_Parameter`, `Parameter_Type` and `Parameter_BaseType` compatibility rules to `Safe` instead of `Low` in the file `modules/RulesBin.xml`.

The rules db file is usually installed to `/usr/share/abi-compliance-checker/modules/RulesBin.xml`.

Thank you for reporting issues!

**Comment by zhuda** [comment]
@lvc Thanks for the information. I am thinking what's the better way to do this. I may can help contribute somehow. 

For the parameter type changed case, ideally the tool can detect the typedef and report this is not change.  if this is not doable, alternatively we may allow user to specify two equivalent types, which one do you think  is easier to achieve?

**Comment by aponomarenko** [comment]
This change may indicate break of **behavioral** binary compatibility and should be detected as Low-severity change by default. For some libraries this is not the case, but we should detect and report it in general case.

**Comment by zhuda** [comment]
btw I saw there is a commit [fix typedef](https://github.com/lvc/abi-compliance-checker/commit/b85859e8d5e0e9a4daeb2e02244d2fceed32c9af) will that be the fix for recognize typedef types?

**Comment by aponomarenko** [comment]
This commit fixes loop hanging when undecorating typedef-based data types.
